name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: sudo apt-get update && sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - run: pnpm nx build mat-extended
      - run: pnpm nx test mat-extended
      - run: pnpm nx lint mat-extended
      - run: pnpm nx nx-release-publish mat-extended
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
